// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD_310_W22SD_Assignment.Models;

#nullable disable

namespace SD_310_W22SD_Assignment.Migrations
{
    [DbContext(typeof(MyTunesContext))]
    partial class MyTunesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Rating1")
                        .HasColumnType("int")
                        .HasColumnName("Rating");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Collection", b =>
                {
                    b.HasOne("SD_310_W22SD_Assignment.Models.Song", "Song")
                        .WithMany("Collections")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("FK_Collections_Songs");

                    b.HasOne("SD_310_W22SD_Assignment.Models.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Collections_Users");

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Purchase", b =>
                {
                    b.HasOne("SD_310_W22SD_Assignment.Models.Song", "Song")
                        .WithMany("Purchases")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("FK_Purchases_Songs");

                    b.HasOne("SD_310_W22SD_Assignment.Models.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Purchases_Users");

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Rating", b =>
                {
                    b.HasOne("SD_310_W22SD_Assignment.Models.Song", "Song")
                        .WithMany("Ratings")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("FK_Ratings_Songs");

                    b.HasOne("SD_310_W22SD_Assignment.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Ratings_Users");

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Song", b =>
                {
                    b.HasOne("SD_310_W22SD_Assignment.Models.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("FK_Songs_Artists");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Artist", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Song", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Purchases");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.User", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Purchases");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
